version: '2'
services:
  web-dev:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - mongo 
    links:
     - mongo 
    volumes:
     - .:/app
    command:
        ['yarn', 'run', 'dev']
  web-prod:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    command:
        ['yarn', 'run', 'start']
  mongo:
    image: mongo:3.4